add quotes where needed
anywhere that a stray space or other weird character could get into a
command line

diff --git a/bin/git-hg b/bin/git-hg
--- a/bin/git-hg
+++ b/bin/git-hg
@@ -48,9 +48,9 @@ function check-hg-fast-export {
     if type hg-fast-export > /dev/null 2>&1 ; then
 	HG_FAST_EXPORT=hg-fast-export
     else
-	GITHG_HOME=$($canon $(dirname $($canon $0))/..)
+	GITHG_HOME=$($canon "$(dirname "$($canon "$0")")/..")
 	HG_FAST_EXPORT=$GITHG_HOME/fast-export/hg-fast-export.sh
-	if ! type $HG_FAST_EXPORT > /dev/null 2>&1 ; then
+	if ! type "$HG_FAST_EXPORT" > /dev/null 2>&1 ; then
 	    echo "error: executable not found, $HG_FAST_EXPORT"
 	    echo 'Possible fixes: run "git submodule update --init" in git-hg repo, or'
 	    echo 'install hg-fast-export executable in directory on $PATH.'
@@ -69,22 +69,22 @@ function git-hg-clone {
     HG_REMOTE=$1
     
     if [[ $# -lt 2 ]]; then
-        CHECKOUT=$(basename ${1%#*})
+        CHECKOUT=$(basename "${1%#*}")
     else
         CHECKOUT=$2
     fi
     if [[ -a $CHECKOUT ]]; then
-	echo error: $CHECKOUT exists
+	echo "error: $CHECKOUT exists"
 	exit 1
     fi
-    git init $CHECKOUT
-    hg clone -U $HG_REMOTE $CHECKOUT/.git/hgcheckout
+    git init "$CHECKOUT"
+    hg clone -U "$HG_REMOTE" "$CHECKOUT/.git/hgcheckout"
     (
-	cd $CHECKOUT
+	cd "$CHECKOUT"
 	git init --bare .git/hgremote
 	(
 	    cd .git/hgremote
-	    $HG_FAST_EXPORT -r ../hgcheckout $FORCE
+	    "$HG_FAST_EXPORT" -r ../hgcheckout $FORCE
 	)
 	git remote add hg .git/hgremote
 	git fetch hg
@@ -93,8 +93,8 @@ function git-hg-clone {
         else
             local branch=$(cd .git/hgcheckout/ && hg tip | grep branch | awk '{print $2}')
         fi
-        git config hg.tracking.master $branch
-        git pull hg $branch
+        git config hg.tracking.master "$branch"
+        git pull hg "$branch"
     )
 }
 
@@ -107,7 +107,7 @@ function git-hg-fetch {
     hg -R .git/hgcheckout pull
     (
 	cd .git/hgremote
-	$HG_FAST_EXPORT $FORCE
+	"$HG_FAST_EXPORT" $FORCE
     )
     git fetch hg
 }
@@ -147,7 +147,7 @@ function git-hg-pull {
             fi
         fi
     else
-        remote_branch=$(git config hg.tracking.${current_branch} || true)
+        remote_branch=$(git config "hg.tracking.$current_branch" || true)
         if [[ -z $remote_branch ]]; then
              echo "ERROR: Cannot determine the remote branch to pull from. Run git merge manually against the desired remote branch."
              echo "Alternatively, set hg.tracking.$current_branch to the name of the branch in hg the current branch should track"
@@ -156,9 +156,9 @@ function git-hg-pull {
     fi
 
     if [[ "$REBASE" == "--rebase" ]]; then
-        git rebase hg/$remote_branch
+        git rebase "hg/$remote_branch"
     else
-        git merge hg/$remote_branch
+        git merge "hg/$remote_branch"
     fi
 }
 
@@ -168,13 +168,13 @@ function git-hg-checkout {
         shift
     fi
     git-hg-fetch $FORCE
-    git checkout hg/$1 -b $1
+    git checkout "hg/$1" -b "$1"
 }
 
 function git-hg-push {
     HG_REPO=$1
     hg convert . .git/hgcheckout
-    hg -R .git/hgcheckout push $HG_REPO
+    hg -R .git/hgcheckout push "$HG_REPO"
 }
 
 function usage {
